nome=str(input('Digite seu nome completo: ')).strip()
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minusculas é {}' .format(nome.lower()))
print('Seu nome todo tem {} caracteres' .format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras ' .format(nome.find(' ')))
n2 = nome.split()
print('Seu primeiro nome é {} e tem {} letras' .format(n2[0], len(n2[0])))
