n = input('Digite algo:' )
print ('O tipo primitivo é: ' , type(n))
print ('É um numero? ', n.isnumeric())
print ('É uma palavra?', n.isalpha())
print ('Só tem espaço?', n.isspace())
print ('É alfanumerico' , n.isalnum())
print ('É maiusculo', n.isupper())
print ('É minusculo', n.islower())
print ('Esta capitalizada', n.istitle())
